### ISSUE TITLE
id's vs classes

### ISSUE THREAD

**Issue by ad3429** [beccap7/prj-rev-bwfs-dasmoto#1]
https://github.com/beccap7/prj-rev-bwfs-dasmoto/blob/master/DasmotoArt/index.html#L8-L29

It seems you assigned your "price" elements id's, however they should be classes since you are using the same price class for multiple elements to assign them the same stylings. Id's are better suited for unique, individual elements while classes are better for when you want to give a group of elements the same styling. Here is a great resource on the differences between classes and id's:

https://css-tricks.com/the-difference-between-id-and-class/

**Comment by beccap7** [comment]
Thanks for the tip! I'm still trying to figure out the difference between ID's and classes and when it's best to use which
